-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.hospitals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  hospital_name text NOT NULL,
  registration_number text UNIQUE,
  hospital_type text,
  bed_capacity integer,
  license_number text,
  accreditation text,
  contact_person text,
  contact_email text,
  contact_phone text,
  address text,
  city text,
  state text,
  postal_code text,
  latitude numeric,
  longitude numeric,
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hospitals_pkey PRIMARY KEY (id),
  CONSTRAINT hospitals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL,
  reference_id text,
  reference_type text,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id text,
  item_name text NOT NULL,
  quantity integer NOT NULL,
  unit text NOT NULL,
  unit_price numeric NOT NULL,
  total_price numeric NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.purchase_orders(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text NOT NULL,
  role USER-DEFINED NOT NULL,
  organization_name text,
  phone text,
  address text,
  city text,
  state text,
  country text DEFAULT 'India'::text,
  postal_code text,
  avatar_url text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.purchase_orders (
  id text NOT NULL,
  rfq_id text,
  quotation_id text,
  hospital_id uuid,
  vendor_id uuid,
  order_date timestamp with time zone DEFAULT now(),
  delivery_date timestamp with time zone,
  total_amount numeric NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::order_status,
  payment_status USER-DEFINED DEFAULT 'pending'::payment_status,
  payment_terms text,
  delivery_address text,
  special_instructions text,
  created_by uuid,
  approved_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT purchase_orders_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_orders_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES public.quotations(id),
  CONSTRAINT purchase_orders_hospital_id_fkey FOREIGN KEY (hospital_id) REFERENCES public.hospitals(id),
  CONSTRAINT purchase_orders_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT purchase_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT purchase_orders_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.quotation_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  quotation_id text,
  rfq_item_id uuid,
  item_name text NOT NULL,
  quantity integer NOT NULL,
  unit text NOT NULL,
  unit_price numeric NOT NULL,
  total_price numeric NOT NULL,
  brand text,
  manufacturer text,
  specifications text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quotation_items_pkey PRIMARY KEY (id),
  CONSTRAINT quotation_items_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES public.quotations(id),
  CONSTRAINT quotation_items_rfq_item_id_fkey FOREIGN KEY (rfq_item_id) REFERENCES public.rfq_items(id)
);
CREATE TABLE public.quotations (
  id text NOT NULL,
  rfq_id text,
  vendor_id uuid,
  total_amount numeric NOT NULL,
  delivery_time_days integer NOT NULL,
  valid_until timestamp with time zone NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::quotation_status,
  notes text,
  terms text,
  document_url text,
  submitted_at timestamp with time zone DEFAULT now(),
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quotations_pkey PRIMARY KEY (id),
  CONSTRAINT quotations_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT quotations_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.rfq_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  rfq_id text,
  item_name text NOT NULL,
  description text,
  quantity integer NOT NULL,
  unit text NOT NULL,
  specification text,
  estimated_price numeric,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rfq_items_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rfq_line_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rfq_id uuid NOT NULL,
  line_item_id integer NOT NULL,
  inn_name text,
  brand_name text,
  dosage text,
  form text,
  quantity integer,
  unit_of_issue text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rfq_line_items_pkey PRIMARY KEY (id),
  CONSTRAINT rfq_line_items_rfq_id_fkey FOREIGN KEY (rfq_id) REFERENCES public.rfqs(id)
);
CREATE TABLE public.rfqs (
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  title text NOT NULL,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'closed'::text, 'awarded'::text])),
  deadline timestamp with time zone,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rfqs_pkey PRIMARY KEY (id),
  CONSTRAINT rfqs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.vendors (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  vendor_name text NOT NULL,
  company_registration text UNIQUE,
  gst_number text,
  vendor_type text,
  rating numeric DEFAULT 0,
  total_orders integer DEFAULT 0,
  completed_orders integer DEFAULT 0,
  contact_person text,
  contact_email text,
  contact_phone text,
  address text,
  city text,
  state text,
  postal_code text,
  bank_name text,
  bank_account text,
  bank_ifsc text,
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vendors_pkey PRIMARY KEY (id),
  CONSTRAINT vendors_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);